version: '3.4'
name: data-processing-framework
services:
  backend-core:
    hostname: ${CORE_HOST}
    build: https://github.com/Data-Processing-Framework/Backend-Core.git#main
    ports:
      - "5000:5000"
    environment:
      - N_WORKERS=${N_WORKERS}
      - CONTROLLER_REQUEST_PORT=${CONTROLLER_REQUEST_PORT}
      - CONTROLLER_RESPONSE_PORT=${CONTROLLER_RESPONSE_PORT}

  backend-worker:
    build: https://github.com/Data-Processing-Framework/Backend-Worker.git#master
    environment:
      - DATA_PUBLISHER_PORT=${DATA_PUBLISHER_PORT}
      - DATA_SUBSCRIBER_PORT=${DATA_SUBSCRIBER_PORT}
      - CONTROLLER_REQUEST_ADDRESS=tcp://${CORE_HOST}:${CONTROLLER_REQUEST_PORT}
      - CONTROLLER_RESPONSE_ADDRESS=tcp://${CORE_HOST}:${CONTROLLER_RESPONSE_PORT}
      - WORKER_TIMEOUT=${WORKER_TIMEOUT}
      - N_WORKERS= ${N_WORKERS}
    deploy:
      replicas: ${N_WORKERS}

  frontend:
    ports:
      - "80:3000"
    build: https://github.com/Data-Processing-Framework/Frontend.git#main
  