version: '3.4'
name: data-processing-framework
services:
  backend-core:
    hostname: ${CORE_HOST}
    build: https://github.com/Data-Processing-Framework/Backend-Core.git#main
    ports:
      - "5000:5000"
    environment:
      - N_WORKERS=${N_WORKERS}
      - CONTROLLER_REQUEST_PORT=${CONTROLLER_REQUEST_PORT}
      - CONTROLLER_RESPONSE_PORT=${CONTROLLER_RESPONSE_PORT}
      - DEBUG=${CORE_DEBUG}
    volumes:
      - data:/app/app/data:rw

  backend-worker-input:
    build: https://github.com/Data-Processing-Framework/Backend-Worker.git#master
    hostname: ${WORKER_INPUT_HOST}
    environment:
      - DATA_PUBLISHER_ADDRESS=tcp://127.0.0.1:${DATA_PUBLISHER_PORT}
      - INPUT_SUBSCRIBER_ADDRESS=tcp://0.0.0.0:${INPUT_SUBSCRIBER_PORT}
      - INTERNAL_SUBSCRIBER_ADDRESS=tcp://127.0.0.1:${INTERNAL_SUBSCRIBER_PORT}
      - INTERNAL_PUBLISHER_ADDRESS=tcp://127.0.0.1:${INTERNAL_PUBLISHER_PORT}

      - CONTROLLER_REQUEST_ADDRESS=tcp://${CORE_HOST}:${CONTROLLER_REQUEST_PORT}
      - CONTROLLER_RESPONSE_ADDRESS=tcp://${CORE_HOST}:${CONTROLLER_RESPONSE_PORT}
      - WORKER_TIMEOUT=${WORKER_TIMEOUT}
      - N_WORKERS= ${N_WORKERS}
      - IS_INPUT=1
      - DEBUG=${INPUT_DEBUG}
    depends_on:
      - backend-core
    volumes:
      - data:/app/src/data:ro

  backend-worker:
    build: https://github.com/Data-Processing-Framework/Backend-Worker.git#master
    environment:
      - DATA_PUBLISHER_ADDRESS=tcp://127.0.0.1:${DATA_PUBLISHER_PORT}
      - INPUT_SUBSCRIBER_ADDRESS=tcp://${WORKER_INPUT_HOST}:${INPUT_SUBSCRIBER_PORT}
      - INTERNAL_SUBSCRIBER_ADDRESS=tcp://127.0.0.1:${INTERNAL_SUBSCRIBER_PORT}
      - INTERNAL_PUBLISHER_ADDRESS=tcp://127.0.0.1:${INTERNAL_PUBLISHER_PORT}

      - CONTROLLER_REQUEST_ADDRESS=tcp://${CORE_HOST}:${CONTROLLER_REQUEST_PORT}
      - CONTROLLER_RESPONSE_ADDRESS=tcp://${CORE_HOST}:${CONTROLLER_RESPONSE_PORT}
      - WORKER_TIMEOUT=${WORKER_TIMEOUT}
      - N_WORKERS= ${N_WORKERS}
      - IS_INPUT=0
      - DEBUG=${WORKER_DEBUG}
    deploy:
      replicas: ${N_WORKERS}
    depends_on:
      - backend-core
    volumes:
      - data:/app/src/data:ro

  frontend:
    ports:
      - "80:3000"
    build: 
      #build from https://github.com/Data-Processing-Framework/Frontend.git#main
      context: https://github.com/Data-Processing-Framework/Frontend.git#main
      args:
        - CORE_ADDRESS=http://localhost:5000

  log_db:
    image: mysql
    hostname: ${LOGGING_DB_HOST}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${LOGGING_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${LOGGING_DB_PASSWORD}
      - MYSQL_USER=${LOGGING_DB_USER}
      - MYSQL_DATABASE=${LOGGING_DB_NAME}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - logs:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql

volumes:
  data:
  logs: