CREATE TABLE IF NOT EXISTS `Workers`(
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `log_level` INT NULL,
    `log_levelname` CHAR(32) NULL,
    `log` TEXT(2048) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created_by` CHAR(32) NOT NULL,
    `type` CHAR(32) NOT NULL,
    `name` CHAR(32) NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE EVENT IF NOT EXISTS clean_old_records
ON SCHEDULE EVERY 1 DAY
STARTS (TIMESTAMP(CURDATE()) + INTERVAL 1 DAY)
DO 
DELETE FROM Workers WHERE created_at < NOW() - INTERVAL 30 DAY;